### ISSUE TITLE
Dataset URL not working

### ISSUE THREAD

**Issue by seedatnabeel** [MingyuJ666/ProLLM#3]
Hi. Thanks for the really awesome paper!

I am trying to access the datasets via the URL on the readme, however the link seems to have expired:
https://drive.google.com/drive/folders/19h8ekwKjvSS48Il_AQbUMfi8nDeCuivu?usp=sharing

Please would it be possible to share an update on how to access the different datasets that work with the pipeline.

Thanks in advance :)

**Comment by haochen-MBZUAI** [comment]
Thanks for your kindly remind. We have updated our dataset link.😀

**Comment by seedatnabeel** [comment]
Thanks @tiuxuxsh76075 ! The link still requires authorization to access the Google drive --- is it possible to please make it available for public access :)

**Comment by seedatnabeel** [comment]
Thanks for the updates on the URL :)
